import type { Language } from '@/i18n';
import type { CountryCode } from '@/types';

/** ISO 3166-1 alpha-2 code to its flag emoji (two regional-indicator symbols). */
export const flagOf = (code: string) => String.fromCodePoint(...[...code].map((char) => 0x1f1a5 + char.charCodeAt(0)));

export interface Country {
  id: CountryCode;
  emoji: string;
  names: Record<Language, string>;
}

/** [ISO code, English, Russian, Uzbek] for every UN member and observer state plus common territories. */
const RAW: readonly (readonly [string, string, string, string])[] = [
  ['AF', 'Afghanistan', 'Афганистан', 'Afgʻoniston'],
  ['AL', 'Albania', 'Албания', 'Albaniya'],
  ['DZ', 'Algeria', 'Алжир', 'Jazoir'],
  ['AD', 'Andorra', 'Андорра', 'Andorra'],
  ['AO', 'Angola', 'Ангола', 'Angola'],
  ['AG', 'Antigua and Barbuda', 'Антигуа и Барбуда', 'Antigua va Barbuda'],
  ['AR', 'Argentina', 'Аргентина', 'Argentina'],
  ['AM', 'Armenia', 'Армения', 'Armaniston'],
  ['AU', 'Australia', 'Австралия', 'Avstraliya'],
  ['AT', 'Austria', 'Австрия', 'Avstriya'],
  ['AZ', 'Azerbaijan', 'Азербайджан', 'Ozarbayjon'],
  ['BS', 'Bahamas', 'Багамы', 'Bagama orollari'],
  ['BH', 'Bahrain', 'Бахрейн', 'Bahrayn'],
  ['BD', 'Bangladesh', 'Бангладеш', 'Bangladesh'],
  ['BB', 'Barbados', 'Барбадос', 'Barbados'],
  ['BY', 'Belarus', 'Беларусь', 'Belarus'],
  ['BE', 'Belgium', 'Бельгия', 'Belgiya'],
  ['BZ', 'Belize', 'Белиз', 'Beliz'],
  ['BJ', 'Benin', 'Бенин', 'Benin'],
  ['BT', 'Bhutan', 'Бутан', 'Butan'],
  ['BO', 'Bolivia', 'Боливия', 'Boliviya'],
  ['BA', 'Bosnia and Herzegovina', 'Босния и Герцеговина', 'Bosniya va Gertsegovina'],
  ['BW', 'Botswana', 'Ботсвана', 'Botsvana'],
  ['BR', 'Brazil', 'Бразилия', 'Braziliya'],
  ['BN', 'Brunei', 'Бруней', 'Bruney'],
  ['BG', 'Bulgaria', 'Болгария', 'Bolgariya'],
  ['BF', 'Burkina Faso', 'Буркина-Фасо', 'Burkina-Faso'],
  ['BI', 'Burundi', 'Бурунди', 'Burundi'],
  ['CV', 'Cabo Verde', 'Кабо-Верде', 'Kabo-Verde'],
  ['KH', 'Cambodia', 'Камбоджа', 'Kambodja'],
  ['CM', 'Cameroon', 'Камерун', 'Kamerun'],
  ['CA', 'Canada', 'Канада', 'Kanada'],
  ['CF', 'Central African Republic', 'Центральноафриканская Республика', 'Markaziy Afrika Respublikasi'],
  ['TD', 'Chad', 'Чад', 'Chad'],
  ['CL', 'Chile', 'Чили', 'Chili'],
  ['CN', 'China', 'Китай', 'Xitoy'],
  ['CO', 'Colombia', 'Колумбия', 'Kolumbiya'],
  ['KM', 'Comoros', 'Коморы', 'Komor orollari'],
  ['CG', 'Congo', 'Республика Конго', 'Kongo Respublikasi'],
  ['CD', 'DR Congo', 'ДР Конго', 'Kongo DR'],
  ['CR', 'Costa Rica', 'Коста-Рика', 'Kosta-Rika'],
  ['CI', 'Côte d’Ivoire', 'Кот-д’Ивуар', 'Kot-d’Ivuar'],
  ['HR', 'Croatia', 'Хорватия', 'Xorvatiya'],
  ['CU', 'Cuba', 'Куба', 'Kuba'],
  ['CY', 'Cyprus', 'Кипр', 'Kipr'],
  ['CZ', 'Czechia', 'Чехия', 'Chexiya'],
  ['DK', 'Denmark', 'Дания', 'Daniya'],
  ['DJ', 'Djibouti', 'Джибути', 'Jibuti'],
  ['DM', 'Dominica', 'Доминика', 'Dominika'],
  ['DO', 'Dominican Republic', 'Доминиканская Республика', 'Dominikan Respublikasi'],
  ['EC', 'Ecuador', 'Эквадор', 'Ekvador'],
  ['EG', 'Egypt', 'Египет', 'Misr'],
  ['SV', 'El Salvador', 'Сальвадор', 'Salvador'],
  ['GQ', 'Equatorial Guinea', 'Экваториальная Гвинея', 'Ekvatorial Gvineya'],
  ['ER', 'Eritrea', 'Эритрея', 'Eritreya'],
  ['EE', 'Estonia', 'Эстония', 'Estoniya'],
  ['SZ', 'Eswatini', 'Эсватини', 'Esvatini'],
  ['ET', 'Ethiopia', 'Эфиопия', 'Efiopiya'],
  ['FJ', 'Fiji', 'Фиджи', 'Fiji'],
  ['FI', 'Finland', 'Финляндия', 'Finlyandiya'],
  ['FR', 'France', 'Франция', 'Fransiya'],
  ['GA', 'Gabon', 'Габон', 'Gabon'],
  ['GM', 'Gambia', 'Гамбия', 'Gambiya'],
  ['GE', 'Georgia', 'Грузия', 'Gruziya'],
  ['DE', 'Germany', 'Германия', 'Germaniya'],
  ['GH', 'Ghana', 'Гана', 'Gana'],
  ['GR', 'Greece', 'Греция', 'Gretsiya'],
  ['GD', 'Grenada', 'Гренада', 'Grenada'],
  ['GT', 'Guatemala', 'Гватемала', 'Gvatemala'],
  ['GN', 'Guinea', 'Гвинея', 'Gvineya'],
  ['GW', 'Guinea-Bissau', 'Гвинея-Бисау', 'Gvineya-Bisau'],
  ['GY', 'Guyana', 'Гайана', 'Gayana'],
  ['HT', 'Haiti', 'Гаити', 'Gaiti'],
  ['HN', 'Honduras', 'Гондурас', 'Gonduras'],
  ['HK', 'Hong Kong', 'Гонконг', 'Gonkong'],
  ['HU', 'Hungary', 'Венгрия', 'Vengriya'],
  ['IS', 'Iceland', 'Исландия', 'Islandiya'],
  ['IN', 'India', 'Индия', 'Hindiston'],
  ['ID', 'Indonesia', 'Индонезия', 'Indoneziya'],
  ['IR', 'Iran', 'Иран', 'Eron'],
  ['IQ', 'Iraq', 'Ирак', 'Iroq'],
  ['IE', 'Ireland', 'Ирландия', 'Irlandiya'],
  ['IL', 'Israel', 'Израиль', 'Isroil'],
  ['IT', 'Italy', 'Италия', 'Italiya'],
  ['JM', 'Jamaica', 'Ямайка', 'Yamayka'],
  ['JP', 'Japan', 'Япония', 'Yaponiya'],
  ['JO', 'Jordan', 'Иордания', 'Iordaniya'],
  ['KZ', 'Kazakhstan', 'Казахстан', 'Qozogʻiston'],
  ['KE', 'Kenya', 'Кения', 'Keniya'],
  ['KI', 'Kiribati', 'Кирибати', 'Kiribati'],
  ['XK', 'Kosovo', 'Косово', 'Kosovo'],
  ['KW', 'Kuwait', 'Кувейт', 'Quvayt'],
  ['KG', 'Kyrgyzstan', 'Киргизия', 'Qirgʻiziston'],
  ['LA', 'Laos', 'Лаос', 'Laos'],
  ['LV', 'Latvia', 'Латвия', 'Latviya'],
  ['LB', 'Lebanon', 'Ливан', 'Livan'],
  ['LS', 'Lesotho', 'Лесото', 'Lesoto'],
  ['LR', 'Liberia', 'Либерия', 'Liberiya'],
  ['LY', 'Libya', 'Ливия', 'Liviya'],
  ['LI', 'Liechtenstein', 'Лихтенштейн', 'Lixtenshteyn'],
  ['LT', 'Lithuania', 'Литва', 'Litva'],
  ['LU', 'Luxembourg', 'Люксембург', 'Lyuksemburg'],
  ['MO', 'Macao', 'Макао', 'Makao'],
  ['MG', 'Madagascar', 'Мадагаскар', 'Madagaskar'],
  ['MW', 'Malawi', 'Малави', 'Malavi'],
  ['MY', 'Malaysia', 'Малайзия', 'Malayziya'],
  ['MV', 'Maldives', 'Мальдивы', 'Maldiv orollari'],
  ['ML', 'Mali', 'Мали', 'Mali'],
  ['MT', 'Malta', 'Мальта', 'Malta'],
  ['MH', 'Marshall Islands', 'Маршалловы Острова', 'Marshall orollari'],
  ['MR', 'Mauritania', 'Мавритания', 'Mavritaniya'],
  ['MU', 'Mauritius', 'Маврикий', 'Mavrikiy'],
  ['MX', 'Mexico', 'Мексика', 'Meksika'],
  ['FM', 'Micronesia', 'Микронезия', 'Mikroneziya'],
  ['MD', 'Moldova', 'Молдова', 'Moldova'],
  ['MC', 'Monaco', 'Монако', 'Monako'],
  ['MN', 'Mongolia', 'Монголия', 'Mongoliya'],
  ['ME', 'Montenegro', 'Черногория', 'Chernogoriya'],
  ['MA', 'Morocco', 'Марокко', 'Marokash'],
  ['MZ', 'Mozambique', 'Мозамбик', 'Mozambik'],
  ['MM', 'Myanmar', 'Мьянма', 'Myanma'],
  ['NA', 'Namibia', 'Намибия', 'Namibiya'],
  ['NR', 'Nauru', 'Науру', 'Nauru'],
  ['NP', 'Nepal', 'Непал', 'Nepal'],
  ['NL', 'Netherlands', 'Нидерланды', 'Niderlandiya'],
  ['NZ', 'New Zealand', 'Новая Зеландия', 'Yangi Zelandiya'],
  ['NI', 'Nicaragua', 'Никарагуа', 'Nikaragua'],
  ['NE', 'Niger', 'Нигер', 'Niger'],
  ['NG', 'Nigeria', 'Нигерия', 'Nigeriya'],
  ['KP', 'North Korea', 'Северная Корея', 'Shimoliy Koreya'],
  ['MK', 'North Macedonia', 'Северная Македония', 'Shimoliy Makedoniya'],
  ['NO', 'Norway', 'Норвегия', 'Norvegiya'],
  ['OM', 'Oman', 'Оман', 'Ummon'],
  ['PK', 'Pakistan', 'Пакистан', 'Pokiston'],
  ['PW', 'Palau', 'Палау', 'Palau'],
  ['PS', 'Palestine', 'Палестина', 'Falastin'],
  ['PA', 'Panama', 'Панама', 'Panama'],
  ['PG', 'Papua New Guinea', 'Папуа — Новая Гвинея', 'Papua — Yangi Gvineya'],
  ['PY', 'Paraguay', 'Парагвай', 'Paragvay'],
  ['PE', 'Peru', 'Перу', 'Peru'],
  ['PH', 'Philippines', 'Филиппины', 'Filippin'],
  ['PL', 'Poland', 'Польша', 'Polsha'],
  ['PT', 'Portugal', 'Португалия', 'Portugaliya'],
  ['PR', 'Puerto Rico', 'Пуэрто-Рико', 'Puerto-Riko'],
  ['QA', 'Qatar', 'Катар', 'Qatar'],
  ['RO', 'Romania', 'Румыния', 'Ruminiya'],
  ['RU', 'Russia', 'Россия', 'Rossiya'],
  ['RW', 'Rwanda', 'Руанда', 'Ruanda'],
  ['KN', 'Saint Kitts and Nevis', 'Сент-Китс и Невис', 'Sent-Kits va Nevis'],
  ['LC', 'Saint Lucia', 'Сент-Люсия', 'Sent-Lyusiya'],
  ['VC', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины', 'Sent-Vinsent va Grenadinlar'],
  ['WS', 'Samoa', 'Самоа', 'Samoa'],
  ['SM', 'San Marino', 'Сан-Марино', 'San-Marino'],
  ['ST', 'São Tomé and Príncipe', 'Сан-Томе и Принсипи', 'San-Tome va Prinsipi'],
  ['SA', 'Saudi Arabia', 'Саудовская Аравия', 'Saudiya Arabistoni'],
  ['SN', 'Senegal', 'Сенегал', 'Senegal'],
  ['RS', 'Serbia', 'Сербия', 'Serbiya'],
  ['SC', 'Seychelles', 'Сейшелы', 'Seyshel orollari'],
  ['SL', 'Sierra Leone', 'Сьерра-Леоне', 'Syerra-Leone'],
  ['SG', 'Singapore', 'Сингапур', 'Singapur'],
  ['SK', 'Slovakia', 'Словакия', 'Slovakiya'],
  ['SI', 'Slovenia', 'Словения', 'Sloveniya'],
  ['SB', 'Solomon Islands', 'Соломоновы Острова', 'Solomon orollari'],
  ['SO', 'Somalia', 'Сомали', 'Somali'],
  ['ZA', 'South Africa', 'ЮАР', 'Janubiy Afrika'],
  ['KR', 'South Korea', 'Южная Корея', 'Janubiy Koreya'],
  ['SS', 'South Sudan', 'Южный Судан', 'Janubiy Sudan'],
  ['ES', 'Spain', 'Испания', 'Ispaniya'],
  ['LK', 'Sri Lanka', 'Шри-Ланка', 'Shri-Lanka'],
  ['SD', 'Sudan', 'Судан', 'Sudan'],
  ['SR', 'Suriname', 'Суринам', 'Surinam'],
  ['SE', 'Sweden', 'Швеция', 'Shvetsiya'],
  ['CH', 'Switzerland', 'Швейцария', 'Shveytsariya'],
  ['SY', 'Syria', 'Сирия', 'Suriya'],
  ['TW', 'Taiwan', 'Тайвань', 'Tayvan'],
  ['TJ', 'Tajikistan', 'Таджикистан', 'Tojikiston'],
  ['TZ', 'Tanzania', 'Танзания', 'Tanzaniya'],
  ['TH', 'Thailand', 'Таиланд', 'Tailand'],
  ['TL', 'Timor-Leste', 'Восточный Тимор', 'Sharqiy Timor'],
  ['TG', 'Togo', 'Того', 'Togo'],
  ['TO', 'Tonga', 'Тонга', 'Tonga'],
  ['TT', 'Trinidad and Tobago', 'Тринидад и Тобаго', 'Trinidad va Tobago'],
  ['TN', 'Tunisia', 'Тунис', 'Tunis'],
  ['TR', 'Türkiye', 'Турция', 'Turkiya'],
  ['TM', 'Turkmenistan', 'Туркменистан', 'Turkmaniston'],
  ['TV', 'Tuvalu', 'Тувалу', 'Tuvalu'],
  ['UG', 'Uganda', 'Уганда', 'Uganda'],
  ['UA', 'Ukraine', 'Украина', 'Ukraina'],
  ['AE', 'United Arab Emirates', 'ОАЭ', 'Birlashgan Arab Amirliklari'],
  ['GB', 'United Kingdom', 'Великобритания', 'Buyuk Britaniya'],
  ['US', 'United States', 'США', 'Amerika Qoʻshma Shtatlari'],
  ['UY', 'Uruguay', 'Уругвай', 'Urugvay'],
  ['UZ', 'Uzbekistan', 'Узбекистан', 'Oʻzbekiston'],
  ['VU', 'Vanuatu', 'Вануату', 'Vanuatu'],
  ['VA', 'Vatican City', 'Ватикан', 'Vatikan'],
  ['VE', 'Venezuela', 'Венесуэла', 'Venesuela'],
  ['VN', 'Vietnam', 'Вьетнам', 'Vyetnam'],
  ['YE', 'Yemen', 'Йемен', 'Yaman'],
  ['ZM', 'Zambia', 'Замбия', 'Zambiya'],
  ['ZW', 'Zimbabwe', 'Зимбабве', 'Zimbabve'],
];

/** The home countries Russian learners most often come from; shown first, before the full list. */
export const POPULAR_IDS: readonly CountryCode[] = [
  'UZ', 'KZ', 'KG', 'TJ', 'TM', 'AF', 'AZ', 'TR', 'RU', 'UA',
  'BY', 'GE', 'AM', 'KR', 'DE', 'US', 'GB', 'AE', 'CN', 'IN',
];

export const COUNTRIES: readonly Country[] = RAW.map(([id, en, ru, uz]) => ({
  id,
  emoji: flagOf(id),
  names: { en, ru, uz },
}));

const BY_ID = new Map(COUNTRIES.map((country) => [country.id, country]));

export const countryName = (id: CountryCode, language: Language): string | undefined => BY_ID.get(id)?.names[language];

export const englishCountryName = (id: CountryCode): string | undefined => BY_ID.get(id)?.names.en;

export const findCountry = (id: CountryCode | null): Country | undefined => (id ? BY_ID.get(id) : undefined);

/** Lower-case, drop apostrophes/diacritics and fold ё to е so "o'zbek", "Oʻzbek" and "узбек" all match. */
export const normalize = (value: string) =>
  value
    .toLowerCase()
    .replace(/ё/g, 'е')
    .replace(/[ʻʼ’‘'`´]/g, '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '');
